services:
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Example_987
    image: mcr.microsoft.com/mssql/server
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s 
   ports: 
    - 11433:1433
         
       
