# notes - https://github.com/coollabsio/coolify/issues/2361#issuecomment-2323038467 
services:
  db:
    environment:
      - 'MSSQL_SA_PASSWORD=${SERVICE_PASSWORD_SQL}'
      - ACCEPT_EULA=Y
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    volumes:
      - '/data/healthchecks/mssql:/opt/mssql/data'
    restart: unless-stopped
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Example_987 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s 
    ports: 
      - 11433:1433
         
       
